<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>LithosServer</AssemblyName>
    <RootNamespace>Lithos.Server</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Version>$(LithosVersion)</Version>
    <InformationalVersion>$(LithosVersion)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <EmbedPatchedFiles Condition="'$(EmbedPatchedFiles)' == ''">false</EmbedPatchedFiles>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../shared/NativeLibrarySearchPath.cs" Link="NativeLibrarySearchPath.cs" />
    <EmbeddedResource Include="../../forks.json" LogicalName="Lithos.forks.json" />
  </ItemGroup>

  <ItemGroup Condition="'$(EmbedPatchedFiles)' == 'true'">
    <EmbeddedResource Include="../../src/VintagestoryServer/bin/$(Configuration)/$(FrameworkVersion)/VintagestoryServer.dll" LogicalName="Lithos.PatchedRoot.VintagestoryServer.dll" />
    <EmbeddedResource Include="../../src/VintagestoryLib/bin/$(Configuration)/$(FrameworkVersion)/VintagestoryLib.dll" LogicalName="Lithos.PatchedRoot.VintagestoryLib.dll" />
    <EmbeddedResource Include="../../src/bin/$(Configuration)/$(FrameworkVersion)/VintagestoryAPI.dll" LogicalName="Lithos.PatchedRoot.VintagestoryAPI.dll" />
    <EmbeddedResource Include="../../src/bin/$(Configuration)/$(FrameworkVersion)/cairo-sharp.dll" LogicalName="Lithos.PatchedRoot.cairo-sharp.dll" />
    <EmbeddedResource Include="../../src/bin/$(Configuration)/$(FrameworkVersion)/VSCreativeMod.dll" LogicalName="Lithos.PatchedMods.VSCreativeMod.dll" />
    <EmbeddedResource Include="../../src/bin/$(Configuration)/$(FrameworkVersion)/VSEssentials.dll" LogicalName="Lithos.PatchedMods.VSEssentials.dll" />
    <EmbeddedResource Include="../../src/bin/$(Configuration)/$(FrameworkVersion)/VSSurvivalMod.dll" LogicalName="Lithos.PatchedMods.VSSurvivalMod.dll" />
  </ItemGroup>
</Project>
